//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Email", typeof(Email).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;en_content&quot; style=&quot;border-top:1px solid #ddd; margin-top:15px; padding-top:10px;&quot; lang=&quot;en&quot;&gt;
        ///	Welcome {1},&lt;br&gt;&lt;br&gt;
        ///You now have access to the Vessels of Concern (VOC) using your CCG Account:&lt;br&gt;&lt;br&gt;
        ///&lt;a href=&quot;{0}&quot;&gt;{0}&lt;/a&gt;
        ///&lt;/div&gt;
        ///
        ///.
        /// </summary>
        public static string AccessMessage {
            get {
                return ResourceManager.GetString("AccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessels of Concern Access.
        /// </summary>
        public static string AccessTitle {
            get {
                return ResourceManager.GetString("AccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;en_content&quot; style=&quot;border-top:1px solid #ddd; margin-top:15px; padding-top:10px;&quot; lang=&quot;en&quot;&gt;
        ///	Welcome {2},&lt;br&gt;&lt;br&gt;
        ///Please follow the steps outlined to set up your Vessels of Concern (VOC) Account:
        ///&lt;ol&gt;
        ///&lt;li&gt;Follow this link to register your CCG account: &lt;a href=&quot;{0}&quot;&gt; CCG Account Set-up&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;Once you have completed your registration, you will receive a verification email to confirm and activate your CCG account. &lt;/li&gt;
        ///&lt;li&gt;You now have access to the &lt;a href=&quot;{1}&quot;&gt;Vessels of Concern&lt;/a&gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InvitationMessage {
            get {
                return ResourceManager.GetString("InvitationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessels of Concern Invitation.
        /// </summary>
        public static string InvitationTitle {
            get {
                return ResourceManager.GetString("InvitationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;&lt;head&gt;&lt;!--[if gte mso 9]&gt;
        ///
        ///&lt;xml&gt;
        ///
        ///    &lt;o:OfficeDocumentSettings&gt;
        ///
        ///    &lt;o:AllowPNG/&gt;
        ///
        ///    &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///
        ///    &lt;/o:OfficeDocumentSettings&gt;
        ///
        ///&lt;/xml&gt;
        ///
        ///&lt;![endif]--&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=u [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
    }
}
