using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace DataModel.SeedData
{
    public partial class SeedDataHelper
    {
        public List<Certificate> Certificates = new List<Certificate>()
            {
                new Certificate { Id = 1, DescEng = "", DescFre = "", NameEng = "Master 150 GT, Domestic", NameFre = "Capitaine, jauge brute de 150, navigation intérieure", Active = 1 },
                new Certificate { Id = 2, DescEng = "", DescFre = "", NameEng = "Master 500 GT, Domestic", NameFre = "Capitaine, jauge brute de 500, navigation intérieure", Active = 1 },
                new Certificate { Id = 3, DescEng = "", DescFre = "", NameEng = "Inter-Provincial Journeyman Certification; Heavy Duty Mechanic", NameFre = "Certificat interprovincial de compagnon, mécanicien de machinerie lourde", Active = 1 },
                new Certificate { Id = 4, DescEng = "", DescFre = "", NameEng = "Inter-Provincial Journeyman Certification; Automotive Mechanic", NameFre = "Certificat interprovincial de compagnon, mécanicien d'automobile", Active = 1 },
                new Certificate { Id = 5, DescEng = "", DescFre = "", NameEng = "Marine First Aid", NameFre = "Secourisme en mer", Active = 1 },
                new Certificate { Id = 6, DescEng = "", DescFre = "", NameEng = "Marine Certificate", NameFre = "Certificat de navigation", Active = 1 },
                new Certificate { Id = 7, DescEng = "", DescFre = "", NameEng = "CCG Logistics Officer Certificate", NameFre = "Certificat d'officier de logistique de la GCC", Active = 1 },
                new Certificate { Id = 8, DescEng = "", DescFre = "", NameEng = "Auditor Training Program", NameFre = "Programme de formation d'auditeur", Active = 1 },
                new Certificate { Id = 9, DescEng = "", DescFre = "", NameEng = "Safety Management for Industrial Facilities Certificate", NameFre = "Certificat en gestion de la sécurité des installations industrielles", Active = 1 },
                new Certificate { Id = 10, DescEng = "", DescFre = "", NameEng = "Occupational Health & Safety Certificate", NameFre = "Certificat de santé et de sécurité au travail", Active = 1 },
                new Certificate { Id = 11, DescEng = "", DescFre = "", NameEng = "Accident Investigation Program", NameFre = "Programme d'enquête sur les accidents", Active = 1 },
                new Certificate { Id = 12, DescEng = "", DescFre = "", NameEng = "Red Seal Carpentry Certification", NameFre = "Certificat de charpenterie Sceau rouge", Active = 1 },
                new Certificate { Id = 13, DescEng = "", DescFre = "", NameEng = "Fall Protection Certificate", NameFre = "Certificat de protection contre les chutes", Active = 1 },
                new Certificate { Id = 14, DescEng = "", DescFre = "", NameEng = "SPRAT or IRATA, Level 1", NameFre = "SPRAT ou IRATA, niveau 1", Active = 1 },
                new Certificate { Id = 15, DescEng = "", DescFre = "", NameEng = "Inter-Provincial Journeyman Certification; Heavy Duty Mechanic or Automotive Mechanic", NameFre = "Certificat interprovincial de compagnon, mécanicien de machinerie lourde ou mécanicien d'automobile", Active = 1 },
                new Certificate { Id = 16, DescEng = "", DescFre = "", NameEng = "Painter and Decorator Certificate", NameFre = "Certificat de peintre et décorateur", Active = 1 },
                new Certificate { Id = 17, DescEng = "", DescFre = "", NameEng = "Marine Emergency Duties - Basic Safety", NameFre = "Fonctions d'urgence en mer - Sécurité élémentaire", Active = 1 },
                new Certificate { Id = 18, DescEng = "", DescFre = "", NameEng = "Marine Emergency Duties - Survival Craft / Rescue Boats", NameFre = "Fonctions d'urgence en mer - Embarcations de sauvetage/bateaux de sauvetage", Active = 1 },
                new Certificate { Id = 19, DescEng = "", DescFre = "", NameEng = "Marine Emergency Duties - Proficiency in Advanced Firefighting", NameFre = "Fonctions d'urgence en mer - Maîtrise avancée de la lutte anti-incendie", Active = 1 },
                new Certificate { Id = 20, DescEng = "", DescFre = "", NameEng = "Restricted Operator Certificate-Maritime Commercial (ROC-MC)", NameFre = "Certificat restreint d’opérateur - commercial maritime (CRO-CM)", Active = 1 },
                new Certificate { Id = 21, DescEng = "", DescFre = "", NameEng = "Diver Certification Board of Canada (DCBC) Restricted Surface Supplied Diver Certification", NameFre = "Conseil Canadien de certification en plongée – Système de distribution d’air restreinte en surface", Active = 1 },
                new Certificate { Id = 22, DescEng = "", DescFre = "", NameEng = "First Aid", NameFre = "Secourisme", Active = 1 },
                new Certificate { Id = 23, DescEng = "", DescFre = "", NameEng = "CCG Medic-A Certificate", NameFre = "Formation Medic-A GCC", Active = 1 },
                new Certificate { Id = 24, DescEng = "", DescFre = "", NameEng = "OEM Maintenance Qualification; Technician", NameFre = "Certification du maintenance du fabricants d’équipement d’origine (FEO)", Active = 1 },
                new Certificate { Id = 25, DescEng = "", DescFre = "", NameEng = "Food Safety Training", NameFre = "Formation en sécurité alementaire", Active = 1 },
                new Certificate { Id = 26, DescEng = "", DescFre = "", NameEng = "Ship's Cook or Provincial Standard (Red Seal)", NameFre = "Cuisinier/cuisinère de navire ou Normes provinciales (Sceau roude)", Active = 1 },
                new Certificate { Id = 28, DescEng = "", DescFre = "", NameEng = "Bridge Watch Certificate", NameFre = "Brevet de matelot de quart à la passerelle", Active = 1 },
                new Certificate { Id = 29, DescEng = "", DescFre = "", NameEng = "Engine Room Rating", NameFre = "Matelot de la salle des machines", Active = 1 },
                new Certificate { Id = 30, DescEng = "", DescFre = "", NameEng = "Fourth Class Engineer - Motor", NameFre = "Officier mécanicien de 4e classe, navire à moteur", Active = 1 },
                new Certificate { Id = 31, DescEng = "", DescFre = "", NameEng = "Third Class Engineer - Motor", NameFre = "Officier mécanicien de 3e classe, navire à moteur", Active = 1 },
                new Certificate { Id = 32, DescEng = "", DescFre = "", NameEng = "Second Class Engineer - Motor", NameFre = "Officier mécanicien de 2e classe, navire à moteur", Active = 1 },
                new Certificate { Id = 33, DescEng = "", DescFre = "", NameEng = "First Class Engineer - Motor", NameFre = "Officier mécanicien de 1re classe, navire à moteur", Active = 1 },
                new Certificate { Id = 34, DescEng = "", DescFre = "", NameEng = "General Operators Certificate (GOC)", NameFre = "Certificat général d'opérateur radio (CGO)", Active = 1 },
                new Certificate { Id = 35, DescEng = "", DescFre = "", NameEng = "Master Mariner", NameFre = "Capitaine au long cours", Active = 1 },
                new Certificate { Id = 36, DescEng = "", DescFre = "", NameEng = "Master 3000 GT", NameFre = "Capitaine, jauge brute de 3 000", Active = 1 },
                new Certificate { Id = 37, DescEng = "", DescFre = "", NameEng = "Small Vessel Safety (MED A2)", NameFre = "Sécurité des petits bâtiments (FUM A2)", Active = 1 },
                new Certificate { Id = 38, DescEng = "", DescFre = "", NameEng = "Watchkeeping Mate, Near Coastal", NameFre = "Officier de pont de quart, à proximité du littoral", Active = 1 },
                new Certificate { Id = 39, DescEng = "", DescFre = "", NameEng = "Master, Near Coastal", NameFre = "Capitaine, à proximité du littoral", Active = 1 },
                new Certificate { Id = 40, DescEng = "", DescFre = "", NameEng = "Logistics Officer Certificate", NameFre = "Certificat d'officier de la logistique de la GCC", Active = 1 },
                new Certificate { Id = 41, DescEng = "", DescFre = "", NameEng = "CCG Electrical Certificate", NameFre = "Certificat d’officier électricien GCC", Active = 1 },
                new Certificate { Id = 42, DescEng = "", DescFre = "", NameEng = "Fishing Master, Third Class", NameFre = "Capitaine de pêche, troisième classe", Active = 1 },
                new Certificate { Id = 43, DescEng = "", DescFre = "", NameEng = "Standard on Training, Certification and Watchkeeping (STCW)", NameFre = "Normes de formation des gens de mer, de délivrance des brevets et de veille (STCW)", Active = 1 },
                new Certificate { Id = 44, DescEng = "", DescFre = "", NameEng = "Cardiopulmonary Resuscitation (CPR)", NameFre = "Réanimation cardiorespiratoire (RCR)", Active = 1 },
                new Certificate { Id = 45, DescEng = "", DescFre = "", NameEng = "Automated External Defibrillator (AED)", NameFre = "Défibrillateur externe automatisé (DEA)", Active = 1 },
                new Certificate { Id = 46, DescEng = "", DescFre = "", NameEng = "Marine Advanced First Aid", NameFre = "Secourisme avancé en mer", Active = 1 },
                new Certificate { Id = 47, DescEng = "", DescFre = "", NameEng = "Advance Cardiac Life Support; Valid ACLS", NameFre = "Soins avancés de réanimation cardiaque; valide SARC", Active = 1 },
                new Certificate { Id = 48, DescEng = "", DescFre = "", NameEng = "Trauma Nursing Core Course (TNCC); Certification from Emergency Nursing Association", NameFre = "Cours de base en soins infirmiers en traumatologie (CBSIT); certification de l'Association des infirmières et infirmiers d'urgence", Active = 1 },
                new Certificate { Id = 49, DescEng = "", DescFre = "", NameEng = "Certified Nurse Practitioner", NameFre = "Infirmière praticienne certifiée", Active = 1 },
                new Certificate { Id = 50, DescEng = "", DescFre = "", NameEng = "Combitube Procedure Training Certification", NameFre = "Certification de la formation sur les procédures en tubes combinés", Active = 1 },
                new Certificate { Id = 51, DescEng = "", DescFre = "", NameEng = "Material or Supply Chain Management Certification", NameFre = "Certification des matériaux ou de la chaîne d'approvisionnement", Active = 1 },
                new Certificate { Id = 52, DescEng = "", DescFre = "", NameEng = "Certified Fitness Professional Program", NameFre = "Programme de conditionnement physique certifié", Active = 1 },
                new Certificate { Id = 53, DescEng = "", DescFre = "", NameEng = "Food Handlers Certificate, Food Safe Level 1", NameFre = "Certificat de salubrité des aliments, niveau 1", Active = 1 },
                new Certificate { Id = 54, DescEng = "", DescFre = "", NameEng = "Red Seal Cook Certification", NameFre = "Certification Sceau rouge de cuisinier", Active = 1 },
                new Certificate { Id = 55, DescEng = "", DescFre = "", NameEng = "Forklift Operator's Certification", NameFre = "Certificat de conducteur de chariot élévateur à fourche", Active = 1 },
                new Certificate { Id = 56, DescEng = "", DescFre = "", NameEng = "Transportation of Dangerous Goods Air & Ground Certification", NameFre = "Certification du transport aérien et terrestre des marchandises dangereuses", Active = 1 },
                new Certificate { Id = 57, DescEng = "", DescFre = "", NameEng = "Restricted Operator's Certificate (Maritime)", NameFre = "Certificat restreint d'opérateur-Maritime (CRO-M)", Active = 1 },
                new Certificate { Id = 58, DescEng = "", DescFre = "", NameEng = "Basic First Aid", NameFre = "Secourisme de base", Active = 1 },
                new Certificate { Id = 59, DescEng = "", DescFre = "", NameEng = "Marine Communications and Traffic Services Certificate", NameFre = "Certificat de services de communications et de trafic maritimes", Active = 1 },
                new Certificate { Id = 60, DescEng = "", DescFre = "", NameEng = "Inter-Provincial Journeyman Trade Certification; Welding (47.1 and/or 47.2)", NameFre = "Certification interprovinciale des compagnons compagnons ; soudage (47,1 et/ou 47,2)", Active = 1 },
                new Certificate { Id = 61, DescEng = "", DescFre = "", NameEng = "Class 3 with Air Break Endorsement", NameFre = "Classe 3 avec l'Attestation de coupure d'air", Active = 1 },
                new Certificate { Id = 62, DescEng = "", DescFre = "", NameEng = "Mobile Crane Certification (as per provincial requirements)", NameFre = "Certification des grues mobiles (selon les exigences provinciales)", Active = 1 },
                new Certificate { Id = 63, DescEng = "", DescFre = "", NameEng = "Red Seal Industrial Electrician Certification", NameFre = "Certification électricien industriel Sceau rouge", Active = 1 },
                new Certificate { Id = 64, DescEng = "", DescFre = "", NameEng = "Red Seal Diesel Mechanic Certification", NameFre = "Certification de mécanicien diesel Sceau rouge", Active = 1 },
                new Certificate { Id = 65, DescEng = "", DescFre = "", NameEng = "Red Seal Welder Certification", NameFre = "Certification de soudeur Sceau rouge", Active = 1 },
                new Certificate { Id = 66, DescEng = "", DescFre = "", NameEng = "Welding Supervisory Certificate 47.2", NameFre = "Certificat de supervision en soudage 47,2", Active = 1 },
                new Certificate { Id = 67, DescEng = "", DescFre = "", NameEng = "Crane Operator Certificate", NameFre = "Certificat d'opérateur de grue", Active = 1 },
                new Certificate { Id = 68, DescEng = "", DescFre = "", NameEng = "Fall Arrest & Tower Rescue Certification", NameFre = "Certification d'arrêt des chutes et de sauvetage en tour", Active = 1 },
                new Certificate { Id = 69, DescEng = "", DescFre = "", NameEng = "Inter-Provincial Journeyman Certification; Heavy Duty Mechanic, Automotive Mechanic or Fourth Class Engineer - Motor (or higher)", NameFre = "Certificat interprovincial de compagnon ; mécanicien de machinerie lourde, mécanicien d'automobile ou mécanicien-moteur de quatrième classe (ou plus)", Active = 1 },
                new Certificate { Id = 70, DescEng = "", DescFre = "", NameEng = "Marine Service Technician Certificate", NameFre = "Certificat de technicien d'entretien maritime", Active = 1 },
                new Certificate { Id = 71, DescEng = "", DescFre = "", NameEng = "Composites Technician Certification", NameFre = "Certification des techniciens en composites", Active = 1 },
                new Certificate { Id = 72, DescEng = "", DescFre = "", NameEng = "Diesel Mechanic or Mechanical Technician or Outboard Motors Mechanical degree", NameFre = "Technicien mécanicien diesel ou mécanicien ou moteur hors-bord diplôme en mécanique", Active = 1 },
                new Certificate { Id = 73, DescEng = "", DescFre = "", NameEng = "Welder Fabricator Certificate", NameFre = "Certificat de soudeurs-fabricants", Active = 1 },
                new Certificate { Id = 74, DescEng = "", DescFre = "", NameEng = "Heavy Duty Mechanic Certification", NameFre = "Certificat de mécanicien de machinerie lourde", Active = 1 },
                new Certificate { Id = 75, DescEng = "", DescFre = "", NameEng = "Red Seal Electrical Trade Certification or Marine Electrician", NameFre = "Certificat de compétence en électricité Sceau rouge ou électricien de marine", Active = 1 },
                new Certificate { Id = 76, DescEng = "", DescFre = "", NameEng = "Protective Coating Technician (NACE) or Marine Coating Applicator", NameFre = "Technicien en revêtements de protection (NACE) ou applicateur de revêtements marins", Active = 1 },
                new Certificate { Id = 77, DescEng = "", DescFre = "", NameEng = "Refrigeration and Air Conditioning Certificate", NameFre = "Certificat en réfrigération et climatisation", Active = 1 },
                new Certificate { Id = 78, DescEng = "", DescFre = "", NameEng = "Red Seal Certification; Painter and Decorator", NameFre = "Certification Sceau rouge; Peintre et décorateur", Active = 1 },
                new Certificate { Id = 79, DescEng = "", DescFre = "", NameEng = "Spill Response Training Certificate", NameFre = "Certificat de formation en intervention en cas de déversement", Active = 1 },
                new Certificate { Id = 80, DescEng = "", DescFre = "", NameEng = "Incident Command System Level 200 or higher", NameFre = "Système de commandement d'intervention de niveau 200 ou supérieur", Active = 1 },
                new Certificate { Id = 81, DescEng = "", DescFre = "", NameEng = "CCG VOC Enforcement Designation", NameFre = "Désignation de la GCC pour l'application de la loi sur les VOC", Active = 1 },
                new Certificate { Id = 82, DescEng = "", DescFre = "", NameEng = "CCG Pollution Response Officer", NameFre = "Agent d'intervention antipollution de la GCC", Active = 1 },
                new Certificate { Id = 83, DescEng = "", DescFre = "", NameEng = "CCG Rescue Specialist Certification", NameFre = "Certification de spécialiste en sauvetage de la GCC", Active = 1 },
                new Certificate { Id = 84, DescEng = "", DescFre = "", NameEng = "CCG SAR Mission Coordinator Certification", NameFre = "Certification du coordonnateur de mission SAR de la GCC", Active = 1 },
                new Certificate { Id = 85, DescEng = "", DescFre = "", NameEng = "Maritime Command Naval Officer Professional Qualification (NOPQ)", NameFre = "Qualification professionnelle d'officier de marine du Commandement maritime (NOPQ)", Active = 1 },
                new Certificate { Id = 86, DescEng = "", DescFre = "", NameEng = "Watchkeeping Mate Certificate", NameFre = "Officier de pont de quart", Active = 1 },
                new Certificate { Id = 87, DescEng = "", DescFre = "", NameEng = "Chief Mate, Near Coastal", NameFre = "Premier officier de pont, à proximité du littoral", Active = 1 },
                new Certificate { Id = 88, DescEng = "", DescFre = "", NameEng = "Transport Canada Certificate of Competency, Marine Engineering: Third or Fourth Class", NameFre = "Transport Canada Certificate of Competency, Marine Engineering: Third or Fourth Class", Active = 1 },
                new Certificate { Id = 89, DescEng = "", DescFre = "", NameEng = "Transport Canada Certificate of Engineering (including ACV Engineering Class 1 or 2 and Aircraft Maintenance)", NameFre = "Transport Canada Certificate of Engineering (including ACV Engineering Class 1 or 2 and Aircraft Maintenance)", Active = 1 },
                new Certificate { Id = 90, DescEng = "", DescFre = "", NameEng = "Transport Canada Certificate of Competency, First or Second or Third Class Marine Engineering", NameFre = "Transport Canada Certificate of Competency, First or Second or Third Class Marine Engineering", Active = 1 },
                new Certificate { Id = 91, DescEng = "", DescFre = "", NameEng = "Red Seal Technical Trade Certification or Fourth Class Marine Engineering", NameFre = "Red Seal Technical Trade Certification or Fourth Class Marine Engineering", Active = 1 },
                new Certificate { Id = 92, DescEng = "", DescFre = "", NameEng = "Small Vessel Operator Proficiency (SVOP)", NameFre = "Certificat de formation de conducteur de petits bâtiments", Active = 1 },
                new Certificate { Id = 93, DescEng = "", DescFre = "", NameEng = "General Operators Certificate (GOC)", NameFre = "Certificat d'opérateur général (COG)", Active = 1 },
                new Certificate { Id = 94, DescEng = "", DescFre = "", NameEng = "Project Management Professional, Certified", NameFre = "Professionnel de la gestion de projet, certifié", Active = 1 },
                new Certificate { Id = 95, DescEng = "", DescFre = "", NameEng = "IT Security Certification", NameFre = "Certification de sécurité informatique", Active = 1 },
                new Certificate { Id = 96, DescEng = "", DescFre = "", NameEng = "MELDEV Program, Entry Level", NameFre = "Programme PELM, niveau d’entrée", Active = 1 },
                new Certificate { Id = 97, DescEng = "", DescFre = "", NameEng = "MELDEV Program, Intermediate Level", NameFre = "Programme PELM, niveau intermédiaire", Active = 1 },
                new Certificate { Id = 98, DescEng = "", DescFre = "", NameEng = "MELDEV Program, Final Level", NameFre = "Programme PELM, dernier niveau", Active = 1 },
                new Certificate { Id = 99, DescEng = "", DescFre = "", NameEng = "Electronic Technologist", NameFre = "Technologue en électronique", Active = 1 },
                new Certificate { Id = 100, DescEng = "", DescFre = "", NameEng = "Project Management", NameFre = "Gestion de projet", Active = 1 },
                new Certificate { Id = 101, DescEng = "", DescFre = "", NameEng = "Incident Command System (ICS-300)", NameFre = "Système de commandement d'intervention (SCI-300)", Active = 1 },
                new Certificate { Id = 102, DescEng = "", DescFre = "", NameEng = "Master, Near Coastal", NameFre = "Capitaine, à proximité du littoral", Active = 1 },
                new Certificate { Id = 103, DescEng = "", DescFre = "", NameEng = "Master 500 GT, Near Coastal", NameFre = "Capitaine, jauge brute de 500, à proximité du littoral", Active = 1 },
                new Certificate { Id = 104, DescEng = "", DescFre = "", NameEng = "First Aid or Marine Advanced First Aid", NameFre = "Secourisme ou Secourisme avancé en mer", Active = 1 }
        };
    }
}
