//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG Member.
        /// </summary>
        public static string CCGMember {
            get {
                return ResourceManager.GetString("CCGMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Candidate.
        /// </summary>
        public static string ExternalCandidate {
            get {
                return ResourceManager.GetString("ExternalCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Competency Tool.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of a group of individuals.
        /// </summary>
        public static string PhotoExternal {
            get {
                return ResourceManager.GetString("PhotoExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of a Canadian Coast Guard member.
        /// </summary>
        public static string PhotoMember {
            get {
                return ResourceManager.GetString("PhotoMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of students graduating.
        /// </summary>
        public static string PhotoStudents {
            get {
                return ResourceManager.GetString("PhotoStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin, tell us who you are.
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to search External Canadidates positions.
        /// </summary>
        public static string searchexternal {
            get {
                return ResourceManager.GetString("searchexternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to search CCG Members positions.
        /// </summary>
        public static string searchmember {
            get {
                return ResourceManager.GetString("searchmember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to search student positions.
        /// </summary>
        public static string searchstudent {
            get {
                return ResourceManager.GetString("searchstudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Career Competency Tool. This tool is designed to allow you to search and compare various positions within the Canadian Coast Guard..
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
