// <auto-generated />
using DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataModel.Migrations
{
    [DbContext(typeof(CctDbContext))]
    [Migration("20201111022754_dataseed5")]
    partial class dataseed5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataModel.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompetencyId")
                        .HasColumnType("int");

                    b.Property<string>("RequireIndicatorEng")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("RequireIndicatorFre")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompetencyId = 4,
                            RequireIndicatorEng = "lorem ipsum",
                            RequireIndicatorFre = "lorem ipsum"
                        },
                        new
                        {
                            Id = 2,
                            CompetencyId = 4,
                            RequireIndicatorEng = "lorem ipsum",
                            RequireIndicatorFre = "lorem ipsum"
                        });
                });

            modelBuilder.Entity("DataModel.Competency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("DescFre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("NameEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("NameFre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Competencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescEng = "lorem ipus",
                            DescFre = "lorem ipus",
                            NameEng = "Organizational Knowledge",
                            NameFre = "Connaissances organisationnelles"
                        },
                        new
                        {
                            Id = 2,
                            DescEng = "lorem ipus",
                            DescFre = "lorem ipus",
                            NameEng = "Materiel and Supply Chain Management",
                            NameFre = "Matériel et chaîne d'approvisionnement Gestion"
                        },
                        new
                        {
                            Id = 3,
                            DescEng = "lorem ipus",
                            DescFre = "lorem ipus",
                            NameEng = "Planning and Prioritizing",
                            NameFre = "Planification et établissement des priorités"
                        },
                        new
                        {
                            Id = 4,
                            DescEng = "lorem ipus",
                            DescFre = "lorem ipus",
                            NameEng = "Life-Cycle Asset Management",
                            NameFre = "Gestion du cycle de vie des actifs"
                        },
                        new
                        {
                            Id = 5,
                            DescEng = "lorem ipus",
                            DescFre = "lorem ipus",
                            NameEng = "Inventory Management Systems",
                            NameFre = "Gestion du cycle de vie des actifs"
                        },
                        new
                        {
                            Id = 6,
                            DescEng = "lorem ipus",
                            DescFre = "lorem ipus",
                            NameEng = "Master 150 GT",
                            NameFre = "Master 150 GT"
                        },
                        new
                        {
                            Id = 7,
                            DescEng = "lorem ipus",
                            DescFre = "lorem ipus",
                            NameEng = "Master 1700 GT",
                            NameFre = "Master 1700 GT"
                        });
                });

            modelBuilder.Entity("DataModel.CompetencyLevelRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescEng")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("DescFre")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("CompetencyLevelRequirements");
                });

            modelBuilder.Entity("DataModel.CompetencyRatingGroup", b =>
                {
                    b.Property<int>("CompetencyId")
                        .HasColumnType("int");

                    b.Property<int>("CompetencyRatingLevelId")
                        .HasColumnType("int");

                    b.Property<int>("CompetencyLevelRequirementId")
                        .HasColumnType("int");

                    b.HasKey("CompetencyId", "CompetencyRatingLevelId", "CompetencyLevelRequirementId");

                    b.HasIndex("CompetencyLevelRequirementId");

                    b.HasIndex("CompetencyRatingLevelId");

                    b.ToTable("CompetencyRatingGroups");
                });

            modelBuilder.Entity("DataModel.CompetencyRatingLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescEng")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("DescFre")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("NameEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("NameFre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompetencyRatingLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescEng = "Lorem ipsumEng",
                            DescFre = "Lorem ipsumFra",
                            NameEng = "Fundamental Awareness",
                            NameFre = "activité fondamentale de sensibilisation",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            DescEng = "Lorem ipsumEng",
                            DescFre = "Lorem ipsumFra",
                            NameEng = "Novice",
                            NameFre = "Niveau debutant(e)",
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            DescEng = "Lorem ipsumEng",
                            DescFre = "Lorem ipsumFra",
                            NameEng = "Intermediate",
                            NameFre = "Niveau intermediaire",
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            DescEng = "Lorem ipsumEng",
                            DescFre = "Lorem ipsumFre",
                            NameEng = "Advanced",
                            NameFre = "Niveau avancé",
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            DescEng = "Lorem ipsumEng",
                            DescFre = "Lorem ipsumFre",
                            NameEng = "Expert",
                            NameFre = "Niveau expert",
                            Value = 5
                        });
                });

            modelBuilder.Entity("DataModel.CompetencyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("NameFre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("CompetencyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameEng = "Knowledge Elements",
                            NameFre = "Éléments de connaissance"
                        },
                        new
                        {
                            Id = 2,
                            NameEng = "Technical Elements",
                            NameFre = "Éléments techniques"
                        },
                        new
                        {
                            Id = 3,
                            NameEng = "Behavioural Elements",
                            NameFre = "Éléments comportementaux"
                        },
                        new
                        {
                            Id = 4,
                            NameEng = "Certificates",
                            NameFre = "Certificats"
                        });
                });

            modelBuilder.Entity("DataModel.CompetencyTypeGroup", b =>
                {
                    b.Property<int>("CompetencyId")
                        .HasColumnType("int");

                    b.Property<int>("CompetencyTypeId")
                        .HasColumnType("int");

                    b.HasKey("CompetencyId", "CompetencyTypeId");

                    b.HasIndex("CompetencyTypeId");

                    b.ToTable("CompetencyTypeGroups");

                    b.HasData(
                        new
                        {
                            CompetencyId = 1,
                            CompetencyTypeId = 1
                        },
                        new
                        {
                            CompetencyId = 2,
                            CompetencyTypeId = 2
                        },
                        new
                        {
                            CompetencyId = 3,
                            CompetencyTypeId = 2
                        },
                        new
                        {
                            CompetencyId = 4,
                            CompetencyTypeId = 3
                        },
                        new
                        {
                            CompetencyId = 5,
                            CompetencyTypeId = 3
                        },
                        new
                        {
                            CompetencyId = 6,
                            CompetencyTypeId = 4
                        },
                        new
                        {
                            CompetencyId = 7,
                            CompetencyTypeId = 4
                        });
                });

            modelBuilder.Entity("DataModel.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ValueEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ValueFre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("JobCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ValueEng = "Seagoing",
                            ValueFre = "En mer"
                        },
                        new
                        {
                            Id = 2,
                            ValueEng = "non-seagoing",
                            ValueFre = "non maritime"
                        });
                });

            modelBuilder.Entity("DataModel.JobGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("NameEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("NameFre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("JobGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GT",
                            NameEng = "General Technician",
                            NameFre = "Technicien general"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AS",
                            NameEng = "Admin. Services",
                            NameFre = "Services Admin"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CS",
                            NameEng = "Computer Science",
                            NameFre = "Sciences informatiques"
                        });
                });

            modelBuilder.Entity("DataModel.JobGroupLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LevelValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("JobGroupLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LevelValue = "01"
                        },
                        new
                        {
                            Id = 2,
                            LevelValue = "02"
                        },
                        new
                        {
                            Id = 3,
                            LevelValue = "03"
                        });
                });

            modelBuilder.Entity("DataModel.JobGroupPosition", b =>
                {
                    b.Property<int>("JobGroupId")
                        .HasColumnType("int");

                    b.Property<int>("JobGroupLevelId")
                        .HasColumnType("int");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JobPositionId")
                        .HasColumnType("int");

                    b.Property<int>("JobKeyTaskPerLevelId")
                        .HasColumnType("int");

                    b.Property<int>("JobLocationRegionId")
                        .HasColumnType("int");

                    b.HasKey("JobGroupId", "JobGroupLevelId", "JobCategoryId", "JobPositionId", "JobKeyTaskPerLevelId", "JobLocationRegionId");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("JobGroupLevelId");

                    b.HasIndex("JobKeyTaskPerLevelId");

                    b.HasIndex("JobLocationRegionId");

                    b.HasIndex("JobPositionId");

                    b.ToTable("JobGroupPositions");

                    b.HasData(
                        new
                        {
                            JobGroupId = 1,
                            JobGroupLevelId = 1,
                            JobCategoryId = 1,
                            JobPositionId = 1,
                            JobKeyTaskPerLevelId = 1,
                            JobLocationRegionId = 1
                        },
                        new
                        {
                            JobGroupId = 2,
                            JobGroupLevelId = 2,
                            JobCategoryId = 1,
                            JobPositionId = 2,
                            JobKeyTaskPerLevelId = 2,
                            JobLocationRegionId = 2
                        },
                        new
                        {
                            JobGroupId = 3,
                            JobGroupLevelId = 3,
                            JobCategoryId = 2,
                            JobPositionId = 3,
                            JobKeyTaskPerLevelId = 4,
                            JobLocationRegionId = 3
                        },
                        new
                        {
                            JobGroupId = 3,
                            JobGroupLevelId = 3,
                            JobCategoryId = 2,
                            JobPositionId = 4,
                            JobKeyTaskPerLevelId = 4,
                            JobLocationRegionId = 4
                        });
                });

            modelBuilder.Entity("DataModel.JobKeyTaskPerLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescEng")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("DescFre")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("JobKeyTaskPerLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescEng = "Lorem ipsumEng",
                            DescFre = "Lorem ipsumFra"
                        },
                        new
                        {
                            Id = 2,
                            DescEng = "Lorem ipsumEng",
                            DescFre = "Lorem ipsumFra"
                        },
                        new
                        {
                            Id = 3,
                            DescEng = "Lorem ipsumEng",
                            DescFre = "Lorem ipsumFra"
                        },
                        new
                        {
                            Id = 4,
                            DescEng = "Lorem ipsumEng",
                            DescFre = "Lorem ipsumFra"
                        });
                });

            modelBuilder.Entity("DataModel.JobLocationRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("NameFre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("JobLocationRegions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameEng = "Atlantic",
                            NameFre = "Quebec"
                        },
                        new
                        {
                            Id = 2,
                            NameEng = "Western",
                            NameFre = "Ouest"
                        },
                        new
                        {
                            Id = 3,
                            NameEng = "Arctic",
                            NameFre = "Artique"
                        },
                        new
                        {
                            Id = 4,
                            NameEng = "National Headquarters",
                            NameFre = "siège national"
                        });
                });

            modelBuilder.Entity("DataModel.JobPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TitleEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("TitleFre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("JobPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TitleEng = "Manager",
                            TitleFre = "Gestionnaire"
                        },
                        new
                        {
                            Id = 2,
                            TitleEng = "Technical Advisor",
                            TitleFre = "Conseiller technique"
                        },
                        new
                        {
                            Id = 3,
                            TitleEng = "Business Architect",
                            TitleFre = "Architecte d'affaires"
                        },
                        new
                        {
                            Id = 4,
                            TitleEng = "Project Officer",
                            TitleFre = "Agent de projets"
                        });
                });

            modelBuilder.Entity("DataModel.JobPositionCompetency", b =>
                {
                    b.Property<int>("JobPositionId")
                        .HasColumnType("int");

                    b.Property<int>("CompetencyId")
                        .HasColumnType("int");

                    b.HasKey("JobPositionId", "CompetencyId");

                    b.HasIndex("CompetencyId");

                    b.ToTable("JobPositionCompetencies");

                    b.HasData(
                        new
                        {
                            JobPositionId = 1,
                            CompetencyId = 1
                        },
                        new
                        {
                            JobPositionId = 1,
                            CompetencyId = 2
                        },
                        new
                        {
                            JobPositionId = 1,
                            CompetencyId = 3
                        },
                        new
                        {
                            JobPositionId = 1,
                            CompetencyId = 6
                        },
                        new
                        {
                            JobPositionId = 2,
                            CompetencyId = 4
                        },
                        new
                        {
                            JobPositionId = 2,
                            CompetencyId = 5
                        },
                        new
                        {
                            JobPositionId = 3,
                            CompetencyId = 7
                        },
                        new
                        {
                            JobPositionId = 3,
                            CompetencyId = 4
                        },
                        new
                        {
                            JobPositionId = 4,
                            CompetencyId = 5
                        },
                        new
                        {
                            JobPositionId = 4,
                            CompetencyId = 7
                        });
                });

            modelBuilder.Entity("DataModel.JobRole", b =>
                {
                    b.Property<int>("JobGroupId")
                        .HasColumnType("int");

                    b.Property<int>("JobGroupLevelId")
                        .HasColumnType("int");

                    b.HasKey("JobGroupId", "JobGroupLevelId");

                    b.HasIndex("JobGroupLevelId");

                    b.ToTable("JobRoles");

                    b.HasData(
                        new
                        {
                            JobGroupId = 1,
                            JobGroupLevelId = 1
                        },
                        new
                        {
                            JobGroupId = 2,
                            JobGroupLevelId = 1
                        },
                        new
                        {
                            JobGroupId = 3,
                            JobGroupLevelId = 3
                        },
                        new
                        {
                            JobGroupId = 3,
                            JobGroupLevelId = 2
                        });
                });

            modelBuilder.Entity("DataModel.JobRolePositionCompetency", b =>
                {
                    b.Property<int>("JobGroupId")
                        .HasColumnType("int");

                    b.Property<int>("JobGroupLevelId")
                        .HasColumnType("int");

                    b.Property<int>("JobPositionId")
                        .HasColumnType("int");

                    b.Property<int>("CompetencyId")
                        .HasColumnType("int");

                    b.HasKey("JobGroupId", "JobGroupLevelId", "JobPositionId", "CompetencyId");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("JobGroupLevelId");

                    b.HasIndex("JobPositionId");

                    b.ToTable("JobRolePositionCompetencies");

                    b.HasData(
                        new
                        {
                            JobGroupId = 1,
                            JobGroupLevelId = 1,
                            JobPositionId = 1,
                            CompetencyId = 1
                        },
                        new
                        {
                            JobGroupId = 1,
                            JobGroupLevelId = 1,
                            JobPositionId = 1,
                            CompetencyId = 2
                        },
                        new
                        {
                            JobGroupId = 1,
                            JobGroupLevelId = 1,
                            JobPositionId = 1,
                            CompetencyId = 3
                        },
                        new
                        {
                            JobGroupId = 2,
                            JobGroupLevelId = 3,
                            JobPositionId = 2,
                            CompetencyId = 5
                        },
                        new
                        {
                            JobGroupId = 2,
                            JobGroupLevelId = 3,
                            JobPositionId = 2,
                            CompetencyId = 4
                        },
                        new
                        {
                            JobGroupId = 3,
                            JobGroupLevelId = 2,
                            JobPositionId = 3,
                            CompetencyId = 7
                        },
                        new
                        {
                            JobGroupId = 3,
                            JobGroupLevelId = 2,
                            JobPositionId = 3,
                            CompetencyId = 4
                        },
                        new
                        {
                            JobGroupId = 3,
                            JobGroupLevelId = 2,
                            JobPositionId = 4,
                            CompetencyId = 5
                        },
                        new
                        {
                            JobGroupId = 3,
                            JobGroupLevelId = 2,
                            JobPositionId = 4,
                            CompetencyId = 4
                        });
                });

            modelBuilder.Entity("DataModel.Certificate", b =>
                {
                    b.HasOne("DataModel.Competency", "Competency")
                        .WithMany()
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataModel.CompetencyRatingGroup", b =>
                {
                    b.HasOne("DataModel.Competency", "Competency")
                        .WithMany("CompetencyRatingGroups")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.CompetencyLevelRequirement", "CompetencyLevelRequirement")
                        .WithMany("CompetencyRatingGroups")
                        .HasForeignKey("CompetencyLevelRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.CompetencyRatingLevel", "CompetencyRatingLevel")
                        .WithMany("CompetencyRatingGroups")
                        .HasForeignKey("CompetencyRatingLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataModel.CompetencyTypeGroup", b =>
                {
                    b.HasOne("DataModel.Competency", "Competency")
                        .WithMany("CompetencyTypeGroups")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.CompetencyType", "CompetencyType")
                        .WithMany("CompetencyTypeGroups")
                        .HasForeignKey("CompetencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataModel.JobGroupPosition", b =>
                {
                    b.HasOne("DataModel.JobCategory", "JobCategory")
                        .WithMany("JobGroupPositions")
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.JobGroup", "JobGroup")
                        .WithMany("JobGroupPositions")
                        .HasForeignKey("JobGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.JobGroupLevel", "JobGroupLevel")
                        .WithMany("JobGroupPositions")
                        .HasForeignKey("JobGroupLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.JobKeyTaskPerLevel", "JobKeyTaskPerLevel")
                        .WithMany("JobGroupPositions")
                        .HasForeignKey("JobKeyTaskPerLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.JobLocationRegion", "JobLocationRegion")
                        .WithMany("JobGroupPositions")
                        .HasForeignKey("JobLocationRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataModel.JobPositionCompetency", b =>
                {
                    b.HasOne("DataModel.Competency", "Competency")
                        .WithMany("JobPositionCompetencies")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.JobPosition", "JobPosition")
                        .WithMany("JobPositionCompetencies")
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataModel.JobRole", b =>
                {
                    b.HasOne("DataModel.JobGroup", "JobGroup")
                        .WithMany("JobRoles")
                        .HasForeignKey("JobGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.JobGroupLevel", "JobGroupLevel")
                        .WithMany("JobRoles")
                        .HasForeignKey("JobGroupLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataModel.JobRolePositionCompetency", b =>
                {
                    b.HasOne("DataModel.Competency", "Competency")
                        .WithMany("JobRolePositionCompetencies")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.JobGroup", "JobGroup")
                        .WithMany("JobRolePositionCompetencies")
                        .HasForeignKey("JobGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.JobGroupLevel", "JobGroupLevel")
                        .WithMany("JobRolePositionCompetencies")
                        .HasForeignKey("JobGroupLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.JobPosition", "JobPosition")
                        .WithMany("JobRolePositionCompetencies")
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
