//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.PageNames", typeof(PageNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllCandidateShoreside_FR.
        /// </summary>
        public static string AllCandidateShoreside {
            get {
                return ResourceManager.GetString("AllCandidateShoreside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TousObjectifs.
        /// </summary>
        public static string AllObjective {
            get {
                return ResourceManager.GetString("AllObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TousPositions.
        /// </summary>
        public static string AllPositions {
            get {
                return ResourceManager.GetString("AllPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidat.
        /// </summary>
        public static string Candidate {
            get {
                return ResourceManager.GetString("Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MembreGCC.
        /// </summary>
        public static string CCGMember {
            get {
                return ResourceManager.GetString("CCGMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commun.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipage.
        /// </summary>
        public static string Crew {
            get {
                return ResourceManager.GetString("Crew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NiveauCourrant.
        /// </summary>
        public static string CurrentLevel {
            get {
                return ResourceManager.GetString("CurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionCourrante.
        /// </summary>
        public static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck_FR.
        /// </summary>
        public static string Deck {
            get {
                return ResourceManager.GetString("Deck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering_FR.
        /// </summary>
        public static string Engineering {
            get {
                return ResourceManager.GetString("Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics_FR.
        /// </summary>
        public static string Logistics {
            get {
                return ResourceManager.GetString("Logistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NiveauObjectif.
        /// </summary>
        public static string ObjectiveLevel {
            get {
                return ResourceManager.GetString("ObjectiveLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionObjectif.
        /// </summary>
        public static string ObjectivePosition {
            get {
                return ResourceManager.GetString("ObjectivePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officier.
        /// </summary>
        public static string Officer {
            get {
                return ResourceManager.GetString("Officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marin.
        /// </summary>
        public static string Seagoing {
            get {
                return ResourceManager.GetString("Seagoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeDeRecherche.
        /// </summary>
        public static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoreside_FR.
        /// </summary>
        public static string Shoreside {
            get {
                return ResourceManager.GetString("Shoreside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similaire.
        /// </summary>
        public static string Similar {
            get {
                return ResourceManager.GetString("Similar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailsSimilaire.
        /// </summary>
        public static string SimilarDetails {
            get {
                return ResourceManager.GetString("SimilarDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListeSimilaire.
        /// </summary>
        public static string SimiliarList {
            get {
                return ResourceManager.GetString("SimiliarList", resourceCulture);
            }
        }
    }
}
