//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PDFviews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PDFviews() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.PDFviews", typeof(PDFviews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arctic: The Arctic Region is inclusive of the Yukon North slope, Northwest Territories, Nunavut, Nunavik, Nunatsiavut, and Hudson and James Bay. This boundary is inclusive of Inuit Nunangat..
        /// </summary>
        public static string Arctic {
            get {
                return ResourceManager.GetString("Arctic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arctique: La région de l’Arctique comprend le versant nord du Yukon, les Territoires du Nord-Ouest, le Nunavut, le Nunavik, le Nunatsiavut, la baie d’Hudson et la baie James. Ces limites englobent l’Inuit Nunangat..
        /// </summary>
        public static string Arctique {
            get {
                return ResourceManager.GetString("Arctique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantic: The Atlantic Region consists of New Brunswick, Nova Scotia, Prince Edward Island, and Newfoundland and Labrador, minus the Nunatsiavut region in Labrador..
        /// </summary>
        public static string Atlantic {
            get {
                return ResourceManager.GetString("Atlantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantique : La région de l&apos;Atlantique comprend le Nouveau-Brunswick, la Nouvelle-Écosse, l&apos;Île-du-Prince-Édouard et Terre-Neuve-et-Labrador, moins la région du Nunatsiavut au Labrador..
        /// </summary>
        public static string Atlantique {
            get {
                return ResourceManager.GetString("Atlantique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour elements are the behaviours or attitudes needed for any job with the Canadian Coast Guard. We identified 7 and included a level of competency required for each job..
        /// </summary>
        public static string behavCompDesc {
            get {
                return ResourceManager.GetString("behavCompDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les éléments de comportement sont les comportements ou les attitudes nécessaires pour tout emploi au sein de la Garde côtière canadienne. Nous en avons déterminé sept (7) et inclus un niveau de compétence requis pour chaque poste..
        /// </summary>
        public static string behavCompDescFr {
            get {
                return ResourceManager.GetString("behavCompDescFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEHAVIOURAL ELEMENTS:.
        /// </summary>
        public static string BEHAVIOURAL_ELEMENTS {
            get {
                return ResourceManager.GetString("BEHAVIOURAL ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCG College: The Canadian Coast Guard College is a national maritime training facility located on Cape Breton Island, Nova Scotia. It delivers programs in French and English to support the College’s mission and mandate in marine safety, security and environmental protection..
        /// </summary>
        public static string CCG_College {
            get {
                return ResourceManager.GetString("CCG College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central: The Central Region consists of Ontario and Quebec, minus the Nunavik region in northern Quebec..
        /// </summary>
        public static string Central {
            get {
                return ResourceManager.GetString("Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre: La région du Centre comprend l&apos;Ontario et le Québec, moins la région du Nunavik dans le nord du Québec..
        /// </summary>
        public static string Centre {
            get {
                return ResourceManager.GetString("Centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CERTIFICATIONS.
        /// </summary>
        public static string certifications {
            get {
                return ResourceManager.GetString("certifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTESTATIONS.
        /// </summary>
        public static string certificationsFr {
            get {
                return ResourceManager.GetString("certificationsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collège de la GCC: Le Collège de la Garde côtière canadienne est une installation de formation maritime nationale qui se trouve sur l&apos;île du Cap-Breton, en Nouvelle-Écosse. Il offre des programmes en français et en anglais à l’appui de sa mission et de son mandat en matière de sûreté et de sécurité maritimes et de protection de l’environnement..
        /// </summary>
        public static string Collège_de_la_GCC {
            get {
                return ResourceManager.GetString("Collège de la GCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results comparing the two positions.
        /// </summary>
        public static string compareHeading {
            get {
                return ResourceManager.GetString("compareHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultats comparant les deux positions.
        /// </summary>
        public static string compareHeadingFr {
            get {
                return ResourceManager.GetString("compareHeadingFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Position.
        /// </summary>
        public static string currPosition {
            get {
                return ResourceManager.GetString("currPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position actuelle.
        /// </summary>
        public static string currPositionFr {
            get {
                return ResourceManager.GetString("currPositionFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIFFERING CERTIFICATIONS.
        /// </summary>
        public static string diffCertifications {
            get {
                return ResourceManager.GetString("diffCertifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTESTATIONS DIFFÉRENTES.
        /// </summary>
        public static string diffCertificationsFr {
            get {
                return ResourceManager.GetString("diffCertificationsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIFFERING COMPETENCIES.
        /// </summary>
        public static string diffCompetencies {
            get {
                return ResourceManager.GetString("diffCompetencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPÉTENCES DIFFÉRENTES.
        /// </summary>
        public static string diffCompetenciesFr {
            get {
                return ResourceManager.GetString("diffCompetenciesFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIFFERING REGIONS.
        /// </summary>
        public static string diffRegion {
            get {
                return ResourceManager.GetString("diffRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RÉGIONS DIFFÉRENTES.
        /// </summary>
        public static string diffRegionFr {
            get {
                return ResourceManager.GetString("diffRegionFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÉLÉMENTS DE COMPORTEMENT :.
        /// </summary>
        public static string ÉLÉMENTS_DE_COMPORTEMENT {
            get {
                return ResourceManager.GetString("ÉLÉMENTS DE COMPORTEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÉLÉMENTS DE CONNAISSANCE :.
        /// </summary>
        public static string ÉLÉMENTS_DE_CONNAISSANCE {
            get {
                return ResourceManager.GetString("ÉLÉMENTS DE CONNAISSANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÉLÉMENTS TECHNIQUES :.
        /// </summary>
        public static string ÉLÉMENTS_TECHNIQUES {
            get {
                return ResourceManager.GetString("ÉLÉMENTS TECHNIQUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Position Details.
        /// </summary>
        public static string h2Results {
            get {
                return ResourceManager.GetString("h2Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de la position actuelle.
        /// </summary>
        public static string h2ResultsFr {
            get {
                return ResourceManager.GetString("h2ResultsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge elements are practical or theoretical understanding of a subject. It is the information you need (from past experience or education) to succeed in the position..
        /// </summary>
        public static string knowCompDesc {
            get {
                return ResourceManager.GetString("knowCompDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les éléments de connaissance sont une compréhension pratique ou théorique d’un sujet. Il s’agit des renseignements dont vous avez besoin (à partir de votre expérience ou de vos études) pour réussir dans le poste..
        /// </summary>
        public static string knowCompDescFr {
            get {
                return ResourceManager.GetString("knowCompDescFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KNOWLEDGE ELEMENTS: .
        /// </summary>
        public static string KNOWLEDGE_ELEMENTS {
            get {
                return ResourceManager.GetString("KNOWLEDGE ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL.
        /// </summary>
        public static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIVEAU.
        /// </summary>
        public static string levelFr {
            get {
                return ResourceManager.GetString("levelFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCHING CERTIFICATES.
        /// </summary>
        public static string matchCertifications {
            get {
                return ResourceManager.GetString("matchCertifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTESTATIONS ASSOCIÉES.
        /// </summary>
        public static string matchCertificationsFr {
            get {
                return ResourceManager.GetString("matchCertificationsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCHING COMPETENCIES.
        /// </summary>
        public static string matchCompetencies {
            get {
                return ResourceManager.GetString("matchCompetencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPÉTENCES ASSOCIÉES.
        /// </summary>
        public static string matchCompetenciesFr {
            get {
                return ResourceManager.GetString("matchCompetenciesFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCHING REGIONS.
        /// </summary>
        public static string matchRegion {
            get {
                return ResourceManager.GetString("matchRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RÉGIONS ASSOCIÉES.
        /// </summary>
        public static string matchRegionFr {
            get {
                return ResourceManager.GetString("matchRegionFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.ccg-gcc.gc.ca/college/MCTS-training-formation-SCTM/index-eng.html.
        /// </summary>
        public static string MCTSUrl {
            get {
                return ResourceManager.GetString("MCTSUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.ccg-gcc.gc.ca/college/MCTS-training-formation-SCTM/index-fra.html.
        /// </summary>
        public static string MCTSUrlFr {
            get {
                return ResourceManager.GetString("MCTSUrlFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.ccg-gcc.gc.ca/careers-carrieres/MELDEV-training-formation-PPTEM/index-eng.html.
        /// </summary>
        public static string MELDEVUrl {
            get {
                return ResourceManager.GetString("MELDEVUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.ccg-gcc.gc.ca/careers-carrieres/MELDEV-training-formation-PPTEM/index-fra.html.
        /// </summary>
        public static string MELDEVUrlFr {
            get {
                return ResourceManager.GetString("MELDEVUrlFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/O.
        /// </summary>
        public static string N_A {
            get {
                return ResourceManager.GetString("N/A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Headquarters: The Canadian Coast Guard (CCG) National Headquarters is located in Ottawa, Ontario..
        /// </summary>
        public static string National_Headquarters {
            get {
                return ResourceManager.GetString("National Headquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Certifications.
        /// </summary>
        public static string noCertifications {
            get {
                return ResourceManager.GetString("noCertifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun certificat associées.
        /// </summary>
        public static string noCertificationsFr {
            get {
                return ResourceManager.GetString("noCertificationsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No similar positions are currently available for this position..
        /// </summary>
        public static string noPositions {
            get {
                return ResourceManager.GetString("noPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun poste similaire n&apos;est actuellement disponible pour ce poste..
        /// </summary>
        public static string noPositionsFr {
            get {
                return ResourceManager.GetString("noPositionsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No regions available.
        /// </summary>
        public static string noRegions {
            get {
                return ResourceManager.GetString("noRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune région disponible.
        /// </summary>
        public static string noRegionsFr {
            get {
                return ResourceManager.GetString("noRegionsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seagoing positions available.
        /// </summary>
        public static string noSeagoing {
            get {
                return ResourceManager.GetString("noSeagoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune position en mer disponible.
        /// </summary>
        public static string noSeagoingFr {
            get {
                return ResourceManager.GetString("noSeagoingFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shore side positions available.
        /// </summary>
        public static string noShoreside {
            get {
                return ResourceManager.GetString("noShoreside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune position côté rivage disponible.
        /// </summary>
        public static string noShoresideFr {
            get {
                return ResourceManager.GetString("noShoresideFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouest : La région de l&apos;Ouest comprend la Colombie-Britannique, l&apos;Alberta, la Saskatchewan, le Manitoba et le Yukon, moins le versant du Yukon..
        /// </summary>
        public static string Ouest {
            get {
                return ResourceManager.GetString("Ouest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Development Apprenticeship Program (PDAP).
        /// </summary>
        public static string PDAPText {
            get {
                return ResourceManager.GetString("PDAPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme d&apos;apprentissage de perfectionnement professionnel (PDAP).
        /// </summary>
        public static string PDAPTextFr {
            get {
                return ResourceManager.GetString("PDAPTextFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSITION.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        public static string positionDescription {
            get {
                return ResourceManager.GetString("positionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTIF.
        /// </summary>
        public static string positionDescriptionFr {
            get {
                return ResourceManager.GetString("positionDescriptionFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSITION DETAILS.
        /// </summary>
        public static string positionDetails {
            get {
                return ResourceManager.GetString("positionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÉTAILS DU POSTE.
        /// </summary>
        public static string positionDetailsFr {
            get {
                return ResourceManager.GetString("positionDetailsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTE.
        /// </summary>
        public static string positionFr {
            get {
                return ResourceManager.GetString("positionFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSITION RESULTS.
        /// </summary>
        public static string positionResults {
            get {
                return ResourceManager.GetString("positionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RÉSULTATS DE POSITION.
        /// </summary>
        public static string positionResultsFr {
            get {
                return ResourceManager.GetString("positionResultsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSITION(S).
        /// </summary>
        public static string positions {
            get {
                return ResourceManager.GetString("positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTE(S).
        /// </summary>
        public static string positionsFr {
            get {
                return ResourceManager.GetString("positionsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGIONS.
        /// </summary>
        public static string regions {
            get {
                return ResourceManager.GetString("regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RÉGIONS.
        /// </summary>
        public static string regionsFr {
            get {
                return ResourceManager.GetString("regionsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Position.
        /// </summary>
        public static string selPosition {
            get {
                return ResourceManager.GetString("selPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position sélectionnée.
        /// </summary>
        public static string selPositionFr {
            get {
                return ResourceManager.GetString("selPositionFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siège national: Le siège social national de la Garde côtière canadienne (GCC) est situé à Ottawa, en Ontario..
        /// </summary>
        public static string Siège_national {
            get {
                return ResourceManager.GetString("Siège national", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIMILAR POSITIONS.
        /// </summary>
        public static string simPositions {
            get {
                return ResourceManager.GetString("simPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSITIONS SIMILAIRES.
        /// </summary>
        public static string simPositionsFr {
            get {
                return ResourceManager.GetString("simPositionsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical elements describe abilities to apply knowledge to efficiently perform the job..
        /// </summary>
        public static string techCompDesc {
            get {
                return ResourceManager.GetString("techCompDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les éléments techniques décrivent les capacités d’appliquer les connaissances pour exécuter efficacement le travail..
        /// </summary>
        public static string techCompDescFr {
            get {
                return ResourceManager.GetString("techCompDescFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TECHNICAL ELEMENTS:.
        /// </summary>
        public static string TECHNICAL_ELEMENTS {
            get {
                return ResourceManager.GetString("TECHNICAL ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western: The Western Region consists of British Columbia, Alberta, Saskatchewan, Manitoba and Yukon, minus the Yukon slope..
        /// </summary>
        public static string Western {
            get {
                return ResourceManager.GetString("Western", resourceCulture);
            }
        }
    }
}
