//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources.Pages.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ThemeGcwu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ThemeGcwu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.Pages.Shared._ThemeGcwu", typeof(_ThemeGcwu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr.
        /// </summary>
        public static string AlternateLanguageKey {
            get {
                return ResourceManager.GetString("AlternateLanguageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string AlternateLanguageTitle {
            get {
                return ResourceManager.GetString("AlternateLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Canada.
        /// </summary>
        public static string Government_of_Canada {
            get {
                return ResourceManager.GetString("Government of Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection.
        /// </summary>
        public static string Language_selection {
            get {
                return ResourceManager.GetString("Language selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and menus.
        /// </summary>
        public static string Search_and_menus {
            get {
                return ResourceManager.GetString("Search and menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search website.
        /// </summary>
        public static string Search_website {
            get {
                return ResourceManager.GetString("Search website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to &quot;About this site&quot;.
        /// </summary>
        public static string Skip_to_About_this_site {
            get {
                return ResourceManager.GetString("Skip to About this site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to main content.
        /// </summary>
        public static string Skip_to_main_content {
            get {
                return ResourceManager.GetString("Skip to main content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol of the Government of Canada.
        /// </summary>
        public static string Symbol_of_the_Government_of_Canada {
            get {
                return ResourceManager.GetString("Symbol of the Government of Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Competency Tool.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here:.
        /// </summary>
        public static string You_are_here_ {
            get {
                return ResourceManager.GetString("You are here:", resourceCulture);
            }
        }
    }
}
